### PR TITLE
refactor linkedin field extraction

### PR DESCRIPTION
**Pull request by ricardogsilva**
linkedin OAuth API has changed recently and the response contents have a different structure. This commit adapts the code to be able to fetch `firstName`, `lastName` and `email` from the new structure

fixes #4428

### CODE REVIEW

**Comment by ricardogsilva** [comment]
The CI fails seem unrelated to my changes. I'll rebase with master geonode and try again

**Comment by afabiani** [comment]
@ricardogsilva the travis fails for a test which has already been fixes on GeoNode/master.

Maybe do a pull from GeoNode/master first

**Comment by afabiani** [comment]
@ricardogsilva this one is almost good, there is just a code-format issue which might be related to a more severe error. Can you take a look?

```
flake8 geonode
> geonode/people/profileextractors.py:127:26: F821 undefined name 'localized_names'
```

**Comment by ricardogsilva** [comment]
@afabiani 

Fixed the invalid variable name

**Comment by afabiani** [comment]
@ricardogsilva there are still some errors with the smoke tests

https://travis-ci.org/geosolutions-it/geonode/builds/537733917

```
======================================================================
ERROR: test_extract_email (geonode.people.tests.LinkedInExtractorTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/geosolutions-it/geonode/geonode/people/tests.py", line 176, in test_extract_email
    result = self.extractor.extract_email(self.data)
  File "/home/travis/build/geosolutions-it/geonode/geonode/people/profileextractors.py", line 104, in extract_email
    element = data.get("elements")[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
======================================================================
ERROR: test_extract_first_name (geonode.people.tests.LinkedInExtractorTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/geosolutions-it/geonode/geonode/people/tests.py", line 184, in test_extract_first_name
    result = self.extractor.extract_first_name(self.data)
  File "/home/travis/build/geosolutions-it/geonode/geonode/people/profileextractors.py", line 112, in extract_first_name
    return self._extract_field("firstName", data)
  File "/home/travis/build/geosolutions-it/geonode/geonode/people/profileextractors.py", line 119, in _extract_field
    localized_field_values = data.get(name, {}).get("localized", {})
AttributeError: 'str' object has no attribute 'get'
======================================================================
ERROR: test_extract_last_name (geonode.people.tests.LinkedInExtractorTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/geosolutions-it/geonode/geonode/people/tests.py", line 188, in test_extract_last_name
    result = self.extractor.extract_last_name(self.data)
  File "/home/travis/build/geosolutions-it/geonode/geonode/people/profileextractors.py", line 115, in extract_last_name
    return self._extract_field("lastName", data)
  File "/home/travis/build/geosolutions-it/geonode/geonode/people/profileextractors.py", line 119, in _extract_field
    localized_field_values = data.get(name, {}).get("localized", {})
AttributeError: 'str' object has no attribute 'get'
======================================================================
ERROR: test_extract_organization (geonode.people.tests.LinkedInExtractorTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/geosolutions-it/geonode/geonode/people/tests.py", line 192, in test_extract_organization
    result = self.extractor.extract_organization(self.data)
  File "/home/travis/build/geosolutions-it/geonode/geonode/people/profileextractors.py", line 70, in extract_organization
    raise NotImplementedError
NotImplementedError
======================================================================
ERROR: test_extract_organization_no_positions (geonode.people.tests.LinkedInExtractorTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/geosolutions-it/geonode/geonode/people/tests.py", line 199, in test_extract_organization_no_positions
    result = self.extractor.extract_organization(data)
  File "/home/travis/build/geosolutions-it/geonode/geonode/people/profileextractors.py", line 70, in extract_organization
    raise NotImplementedError
NotImplementedError
======================================================================
ERROR: test_extract_organization_no_positions_position_company (geonode.people.tests.LinkedInExtractorTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/geosolutions-it/geonode/geonode/people/tests.py", line 205, in test_extract_organization_no_positions_position_company
    result = self.extractor.extract_organization(data)
  File "/home/travis/build/geosolutions-it/geonode/geonode/people/profileextractors.py", line 70, in extract_organization
    raise NotImplementedError
NotImplementedError
======================================================================
ERROR: test_extract_organization_no_positions_position_company_name (geonode.people.tests.LinkedInExtractorTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/geosolutions-it/geonode/geonode/people/tests.py", line 211, in test_extract_organization_no_positions_position_company_name
    result = self.extractor.extract_organization(data)
  File "/home/travis/build/geosolutions-it/geonode/geonode/people/profileextractors.py", line 70, in extract_organization
    raise NotImplementedError
NotImplementedError
======================================================================
ERROR: test_extract_position (geonode.people.tests.LinkedInExtractorTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/geosolutions-it/geonode/geonode/people/tests.py", line 215, in test_extract_position
    result = self.extractor.extract_position(self.data)
  File "/home/travis/build/geosolutions-it/geonode/geonode/people/profileextractors.py", line 73, in extract_position
    raise NotImplementedError
NotImplementedError
======================================================================
ERROR: test_extract_position_no_positions (geonode.people.tests.LinkedInExtractorTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/geosolutions-it/geonode/geonode/people/tests.py", line 222, in test_extract_position_no_positions
    result = self.extractor.extract_position(data)
  File "/home/travis/build/geosolutions-it/geonode/geonode/people/profileextractors.py", line 73, in extract_position
    raise NotImplementedError
NotImplementedError
======================================================================
ERROR: test_extract_position_no_positions_position_title (geonode.people.tests.LinkedInExtractorTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/geosolutions-it/geonode/geonode/people/tests.py", line 228, in test_extract_position_no_positions_position_title
    result = self.extractor.extract_position(data)
  File "/home/travis/build/geosolutions-it/geonode/geonode/people/profileextractors.py", line 73, in extract_position
    raise NotImplementedError
NotImplementedError
======================================================================
ERROR: test_extract_profile (geonode.people.tests.LinkedInExtractorTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/geosolutions-it/geonode/geonode/people/tests.py", line 232, in test_extract_profile
    result = self.extractor.extract_profile(self.data)
  File "/home/travis/build/geosolutions-it/geonode/geonode/people/profileextractors.py", line 76, in extract_profile
    raise NotImplementedError
NotImplementedError
======================================================================
ERROR: test_extract_profile_no_headline (geonode.people.tests.LinkedInExtractorTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/geosolutions-it/geonode/geonode/people/tests.py", line 241, in test_extract_profile_no_headline
    result = self.extractor.extract_profile(data)
  File "/home/travis/build/geosolutions-it/geonode/geonode/people/profileextractors.py", line 76, in extract_profile
    raise NotImplementedError
NotImplementedError
======================================================================
ERROR: test_extract_profile_no_headline_and_no_summary (geonode.people.tests.LinkedInExtractorTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/geosolutions-it/geonode/geonode/people/tests.py", line 254, in test_extract_profile_no_headline_and_no_summary
    result = self.extractor.extract_profile(data)
  File "/home/travis/build/geosolutions-it/geonode/geonode/people/profileextractors.py", line 76, in extract_profile
    raise NotImplementedError
NotImplementedError
======================================================================
ERROR: test_extract_profile_no_summary (geonode.people.tests.LinkedInExtractorTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/geosolutions-it/geonode/geonode/people/tests.py", line 247, in test_extract_profile_no_summary
    result = self.extractor.extract_profile(data)
  File "/home/travis/build/geosolutions-it/geonode/geonode/people/profileextractors.py", line 76, in extract_profile
    raise NotImplementedError
NotImplementedError
----------------------------------------------------------------------
Ran 120 tests in 1582.761s
FAILED (errors=14)
```

**Comment by ricardogsilva** [comment]
@afabiani 

Sorry about that, I didn't notice the failing tests.

I've fixed them by updating the response schema in order to comply with the updated linkedin API. I've also removed some tests of the linkedin tests, since the new API does not return some of the fields that were being tests (organization, profile, etc) so there is no point in testing for them

**Pull request merged**
