### PR TITLE
Add management command for social logins

### PR DESCRIPTION
**Pull request by ricardogsilva**
This PR adds a new management command that can be used to configure social login providers that are available through `django_allauth`.

The usual way to configure these providers is to:

1. Enable the providers by adding their apps to the `INSTALLED_APPS` setting
1. Login to django's admin section and then manually add entries to the `Social accounts -> Social applications` section

The proposed implementation adds the `setupsociallogins` management command. This command needs to know, for each allauth provider:
- `client_id`
- `secret_key`

As such, the command takes `--{provider}-client-id` and `--{provider}-secret-key` arguments for each enabled provider. Alternatively, it may also get these parameters from the environment - it looks for variables named `{PROVIDER}_OAUTH2_CLIENT_ID` and `{PROVIDER}_OAUTH2_SECRET_KEY`.

This makes it possible to configure providers automatically by putting these sensitive fields in the environment and then running

```
export FACEBOOK_OAUTH2_CLIENT_ID=123456
export FACEBOOK_OAUTH2_SECRET_KEY=abcdef
export LINKEDIN_OAUTH2_CLIENT_ID=123456
export LINKEDIN_OAUTH2_SECRET_KEY=abcdef

python manage.py setupsociallogins
```

### CODE REVIEW

**Comment by giohappy** [comment]
Why did that GNIP stuff leak into this PR?

**Comment by ricardogsilva** [comment]
This PR was prepared against latest official geonode master branch - maybe it has something to do with that?

**Comment by afabiani** [comment]
@giohappy @ricardogsilva that's ok, those are commits referring the cleanup GNIP
https://github.com/GeoNode/geonode/issues/4311

**Comment by afabiani** [comment]
@ricardogsilva can you please add docs for this mgt command to the docs also?

http://docs.geonode.org/en/master/tutorials/admin/admin_mgmt_commands/index.html

**Comment by ricardogsilva** [comment]
@afabiani sure, Ill update the PR with some docs

**Comment by ricardogsilva** [comment]
@afabiani 

docs added

**Pull request merged**
