### PR TITLE
Feature#650 basic auth middleware

### PR DESCRIPTION
**Pull request by bieganowski**
Allow Basic authenticated with correct credentials in LOCKDOWN mode

### CODE REVIEW

**Review by giohappy — APPROVED** [review]

**Review by afabiani — APPROVED** [review]

**Comment by afabiani** [comment]
[PR](https://github.com/GeoNode/geonode/pull/6939) merged upstream.

Should be backported to 3.1.x too?

**Comment by giohappy** [comment]
no @afabiani 3.x is enough, which is the branch used by GET-IT (right?).

**Comment by afabiani** [comment]
@giohappy GET-IT is using the branch 3.x (aka GeoNode 3.1.x). Currently the PR has been merged on master only (3.2.x)
So, I guess we will need to backport to 3.x too.

**warning**: 3.x does not support the REST API v2

**Comment by giohappy** [comment]
@afabiani you're right, I thought 3.x was the branch for 3.2.x. In any case backporting is only meaningful to 3.x, sinche there's no other Gn 3 branch :)

We don't need API v2 for GET-IT. This basic auth fix is required for the meteoblue APi and API v1 too.

**Comment by afabiani** [comment]
@giohappy done.

**Pull request merged**
