### PR TITLE
Ldap auth backend

### PR DESCRIPTION
**Pull request by ricardogsilva**
This PR adds a new contrib package to geonode with some utilities that allow tighter integration with LDAP servers.

Included in the PR:

-  Updated docs page with instructions on how to use this contrib package and an example configuraton
-  A custom authentication backend that is able to create geonode groups and update users' memberships from the group structure specified in LDAP
-  Some extra utilities that deal with the specifics of geonode groups like maximum size of `title` and `slug` fields

### Note
This PR was prepared against current official geonode master, hence the other commits that are showing here

### CODE REVIEW

**Comment by giohappy** [comment]
@ricardogsilva contrib modules are gone :)
if we want to manage it as a contrib package we must move it to a dedicated repo.

**Comment by simboss** [comment]
@afabiani @giohappy please, provide some guidance here

@ricardogsilva yoou should also clean this PR  (at least squash the commits)

**Comment by ricardogsilva** [comment]
@simboss 

My PR is a single commit. Multiple commits show up here since I based my work on geonode master from the official repo and I guess it is not synced with this fork.

@giohappy, @afabiani please provide some guidance on how I should proceed - I wasn't aware the `geonode.contrib` stuff is going away. IMHO starting a whole project just for this is a bit overkill (needing to maintain another repo, do releases, etc), but I'll follow your lead, as I'm not so much into geonode governance process

**Comment by ricardogsilva** [comment]
I'm retiring this PR in favor of GeoNode/geonode-contribs#2, which is basically a rewrite of this in the new extra contribs repo

**Pull request closed without merging**
