### PR TITLE
[Fixes #252] Change button links to reference the new editors

### LINKED ISSUE #252: notifications improvement
* [ ] drop json configuration, use just notification metric definitions table
* [ ] add proper `is_active` to notification metric check (it's calculated, set to False if there's no value)
* [ ] do not remove old notification metric check records, when updating notification - UI doesn't handle scoping (check for specific OWS, resource, service), so this information will be lost otherwise
* [ ] add scoping template (or predefined scope) for notification check. use case: when notification check should be executed on GeoServer only. Notification Check should have service type set, and all metric checks should be populated with this scope.

* [ ] verify if metrics checked are from last collector run. the problem: collector script may be stopped, no new data in, notifications should track if data provided are newer than last check.

* [ ] add history of detected and sent alerts, so it could be displayed in dashboard

### PR DESCRIPTION
**Pull request by marthamareal**
<Include a few sentences describing the overall goals for this Pull Request>
References  #252

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Review by giohappy — CHANGES_REQUESTED** [review]
@marthamareal the "Return to..." buttons must return to the editor page, not the home page.
For example "Return to Layer" should go to `/viewer/#/layer/{id}` and not `/#/detail/layer/1`.

We must also change the redirection of the "Update" buttons.

**Comment by marthamareal** [comment]
Okay, I will define the path of "Return to..." in mapstore-client, What is the new path for Update.

**Comment by afabiani** [comment]
I see a lot of conflicts

**Comment by marthamareal** [comment]
> @marthamareal the "Return to..." buttons must return to the editor page, not the home page.
> For example "Return to Layer" should go to `/viewer/#/layer/{id}` and not `/#/detail/layer/1`.
> 
> We must also change the redirection of the "Update" buttons.

I have fixed the Return to .. url from the client [here](https://github.com/geosolutions-it/geonode-mapstore-client/pull/238)

**Pull request merged**
